analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_classes_with_only_static_members: ignore
include: package:lint_hard/all.yaml

linter:
  rules:
    avoid_print: false  